apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa-cpu
  namespace: autoscale-lab # IMPORTANT: Same namespace as the Deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-deployment # Name of your Deployment
  minReplicas: 1
  maxReplicas: 18 # Maximum 18 pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # We scale on 60% CPU
        averageUtilization: 60
